FROM richarvey/nginx-php-fpm:latest

COPY . .

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Laravel config
ENV APP_ENV production
ENV APP_DEBUG true
ENV LOG_CHANNEL stderr
ENV APP_NAME "777_Zone"
ENV APP_KEY "base64:HurFQ5MBtlVFCmtxVyKcjZT6I+2FjbxMZ7WIGrU/h2Q="

ENV DB_CONNECTION "mysql"
ENV DB_HOST "pxukqohrckdfo4ty.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"
ENV DB_PORT "3306"
ENV DB_DATABASE "jfomyc1iuc8yy7z3"
ENV DB_USERNAME "hq0lt0bebjaz5l6f"
ENV DB_PASSWORD "h156ufpj897ajveq"

ENV BROADCAST_DRIVER pusher
ENV CACHE_DRIVER file
ENV FILESYSTEM_DISK local
ENV QUEUE_CONNECTION sync
ENV SESSION_DRIVER file
# SESSION_LIFETIME 120

ENV MEMCACHED_HOST 127.0.0.1

ENV REDIS_HOST 127.0.0.1
ENV REDIS_PASSWORD null
ENV REDIS_PORT 6379

ENV MAIL_MAILER smtp
ENV MAIL_HOST smtp.gmail.com
ENV MAIL_PORT 587
ENV MAIL_USERNAME dev.dangtu@gmail.com
ENV MAIL_PASSWORD omuspptzvjtmexxr
ENV MAIL_ENCRYPTION tls
ENV MAIL_FROM_ADDRESS dev.dangtu@gmail.com
ENV MAIL_FROM_NAME "${APP_NAME}"

ENV AWS_ACCESS_KEY_ID 
ENV AWS_SECRET_ACCESS_KEY 
ENV AWS_DEFAULT_REGION us-east-1
ENV AWS_BUCKET 
ENV AWS_USE_PATH_STYLE_ENDPOINT false



ENV VITE_APP_NAME "${APP_NAME}"
ENV VITE_PUSHER_APP_KEY "${PUSHER_APP_KEY}"
ENV VITE_PUSHER_HOST "${PUSHER_HOST}"
ENV VITE_PUSHER_PORT "${PUSHER_PORT}"
ENV VITE_PUSHER_SCHEME "${PUSHER_SCHEME}"
ENV VITE_PUSHER_APP_CLUSTER "${PUSHER_APP_CLUSTER}"

ENV FIREBASE_PROJECT_ID laravel-img
ENV FIREBASE_STORAGE_BUCKET laravel-img.appspot.com


ENV GOOGLE_CLIENT_ID   "897779544333-gdnhhfcmrre0sqnu1t04h31mj8li655t.apps.googleusercontent.com"
ENV GOOGLE_CLIENT_SECRET   "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"


ENV PUSHER_APP_ID 1709144
ENV PUSHER_APP_KEY 390fbd50c1be84dab3ee
ENV PUSHER_APP_SECRET 18fd5909bd732ff7e8cc
ENV PUSHER_HOST 
ENV PUSHER_PORT 443
ENV PUSHER_SCHEME https
ENV PUSHER_APP_CLUSTER ap1





# Allow composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

CMD ["/start.sh"]
